#pragma kernel DistanceNoise

RWStructuredBuffer<float> TargetBuffer;

uint _Size;
float _Radius;
float2 _Center;

[numthreads(8, 8, 1)]
void DistanceNoise(uint3 id : SV_DispatchThreadID)
{
    float2 scaled = float2(0.5 - float(id.x) / _Size + _Center.x, 0.5 - float(id.y) / _Size + _Center.y);
    TargetBuffer[id.x + id.y * _Size] = pow(sqrt(scaled.x * scaled.x * scaled.x * scaled.x + scaled.y * scaled.y * scaled.y * scaled.y), _Radius);
}