#pragma kernel PointsToCenter

StructuredBuffer<float2> PointsBuffer;
RWStructuredBuffer<float> TargetBuffer;

uint _Size;
uint _PointsCount;
float _Threshold;

[numthreads(8, 8, 1)]
void PointsToCenter(uint3 id : SV_DispatchThreadID)
{
    for (uint i = 0; i < _PointsCount; i++)
        if(length(0.5 - PointsBuffer[i]) > _Threshold && uint(TargetBuffer[id.x + id.y * _Size]) == i)
            TargetBuffer[id.x + id.y * _Size] = 0.0;
}